#!/bin/bash
echo "正在提供帮助..."
echo ""
echo ""

echo "📚 Claude Code PM - 项目管理系统"
echo "============================================="
echo ""
echo "🎯 快速开始工作流"
echo "  1. /pm:prd-new <名称>        - 创建新的 PRD"
echo "  2. /pm:prd-parse <名称>      - 将 PRD 转换为史诗"
echo "  3. /pm:epic-decompose <名称> - 分解为任务"
echo "  4. /pm:epic-sync <名称>      - 推送到 GitHub"
echo "  5. /pm:epic-start <名称>     - 开始并行执行"
echo ""
echo "📄 PRD 命令"
echo "  /pm:prd-new <名称>     - 启动新产品需求头脑风暴"
echo "  /pm:prd-parse <名称>   - 将 PRD 转换为实施史诗"
echo "  /pm:prd-list           - 列出所有 PRD"
echo "  /pm:prd-edit <名称>    - 编辑现有 PRD"
echo "  /pm:prd-status         - 显示 PRD 实施状态"
echo ""
echo "📚 史诗命令"
echo "  /pm:epic-decompose <名称> - 将史诗分解为任务文件"
echo "  /pm:epic-sync <名称>      - 将史诗和任务推送到 GitHub"
echo "  /pm:epic-oneshot <名称>   - 一条命令完成分解和同步"
echo "  /pm:epic-list             - 列出所有史诗"
echo "  /pm:epic-show <名称>      - 显示史诗及其任务"
echo "  /pm:epic-status [名称]    - 显示史诗进度"
echo "  /pm:epic-close <名称>     - 标记史诗为已完成"
echo "  /pm:epic-edit <名称>      - 编辑史诗详情"
echo "  /pm:epic-refresh <名称>   - 从任务更新史诗进度"
echo "  /pm:epic-start <名称>     - 启动并行代理执行"
echo ""
echo "📝 问题命令"
echo "  /pm:issue-show <编号>      - 显示问题和子问题"
echo "  /pm:issue-status <编号>    - 检查问题状态"
echo "  /pm:issue-start <编号>     - 使用专用代理开始工作"
echo "  /pm:issue-sync <编号>      - 将更新推送到 GitHub"
echo "  /pm:issue-close <编号>     - 标记问题为已完成"
echo "  /pm:issue-reopen <编号>    - 重新关闭的问题"
echo "  /pm:issue-edit <编号>      - 编辑问题详情"
echo "  /pm:issue-analyze <编号>   - 分析并行工作流"
echo ""
echo "🔄 工作流命令"
echo "  /pm:next               - 显示下一个优先任务"
echo "  /pm:status             - 整体项目仪表板"
echo "  /pm:standup            - 每日站会报告"
echo "  /pm:blocked            - 显示被阻塞的任务"
echo "  /pm:in-progress        - 列出进行中的工作"
echo ""
echo "🔗 同步命令"
echo "  /pm:sync               - 与 GitHub 完全双向同步"
echo "  /pm:import <问题>     - 导入现有的 GitHub 问题"
echo ""
echo "🔧 维护命令"
echo "  /pm:validate           - 检查系统完整性"
echo "  /pm:clean              - 归档已完成工作"
echo "  /pm:search <查询>     - 搜索所有内容"
echo ""
echo "⚙️  设置命令"
echo "  /pm:init               - 安装依赖并配置 GitHub"
echo "  /pm:help               - 显示此帮助信息"
echo ""
echo "💡 提示"
echo "  • 使用 /pm:next 查找可用工作"
echo "  • 运行 /pm:status 获取快速概览"
echo "  • 史诗工作流：prd-new → prd-parse → epic-decompose → epic-sync"
echo "  • 查看 README.md 获取完整文档"

exit 0
