"""Add document management fields to context

Revision ID: 20250917081500
Revises: 20250917153300
Create Date: 2025-09-17 08:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20250917081500'
down_revision: Union[str, None] = '20250917153300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###

    # Document management fields
    op.add_column('contexts', sa.Column('file_name', sa.String(length=500), nullable=True))
    op.add_column('contexts', sa.Column('file_type', sa.String(length=100), nullable=True))
    op.add_column('contexts', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('contexts', sa.Column('document_type', sa.String(length=50), nullable=True))

    # Version control fields
    op.add_column('contexts', sa.Column('version', sa.String(length=20), server_default='1.0', nullable=False))
    op.add_column('contexts', sa.Column('parent_version_id', sa.Integer(), nullable=True))
    op.add_column('contexts', sa.Column('is_latest', sa.Boolean(), server_default='true', nullable=False))

    # Permission management fields
    op.add_column('contexts', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('contexts', sa.Column('access_level', sa.String(length=20), server_default='private', nullable=False))
    op.add_column('contexts', sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    # Vector search support fields
    op.add_column('contexts', sa.Column('vector_id', sa.String(length=100), nullable=True))
    op.add_column('contexts', sa.Column('is_embedded', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('contexts', sa.Column('embedding_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    # Content processing status fields
    op.add_column('contexts', sa.Column('processing_status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('contexts', sa.Column('chunks_count', sa.Integer(), nullable=True))

    # Create foreign key constraints
    op.create_foreign_key(
        'fk_context_parent_version', 'contexts', 'contexts',
        ['parent_version_id'], ['id']
    )
    op.create_foreign_key(
        'fk_context_owner', 'contexts', 'users',
        ['owner_id'], ['id']
    )

    # Create indexes for better performance
    op.create_index('idx_context_version', 'contexts', ['version'])
    op.create_index('idx_context_access_level', 'contexts', ['access_level'])
    op.create_index('idx_context_owner_id', 'contexts', ['owner_id'])
    op.create_index('idx_context_document_type', 'contexts', ['document_type'])
    op.create_index('idx_context_processing_status', 'contexts', ['processing_status'])
    op.create_index('idx_context_vector_id', 'contexts', ['vector_id'])
    op.create_index('idx_context_is_latest', 'contexts', ['is_latest'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###

    # Drop indexes
    op.drop_index('idx_context_is_latest', table_name='contexts')
    op.drop_index('idx_context_vector_id', table_name='contexts')
    op.drop_index('idx_context_processing_status', table_name='contexts')
    op.drop_index('idx_context_document_type', table_name='contexts')
    op.drop_index('idx_context_owner_id', table_name='contexts')
    op.drop_index('idx_context_access_level', table_name='contexts')
    op.drop_index('idx_context_version', table_name='contexts')

    # Drop foreign key constraints
    op.drop_constraint('fk_context_owner', 'contexts', type_='foreignkey')
    op.drop_constraint('fk_context_parent_version', 'contexts', type_='foreignkey')

    # Drop columns
    op.drop_column('contexts', 'chunks_count')
    op.drop_column('contexts', 'processing_status')
    op.drop_column('contexts', 'embedding_metadata')
    op.drop_column('contexts', 'is_embedded')
    op.drop_column('contexts', 'vector_id')
    op.drop_column('contexts', 'permissions')
    op.drop_column('contexts', 'access_level')
    op.drop_column('contexts', 'owner_id')
    op.drop_column('contexts', 'is_latest')
    op.drop_column('contexts', 'parent_version_id')
    op.drop_column('contexts', 'version')
    op.drop_column('contexts', 'document_type')
    op.drop_column('contexts', 'file_size')
    op.drop_column('contexts', 'file_type')
    op.drop_column('contexts', 'file_name')

    # ### end Alembic commands ###