"""Add agent registry fields

Revision ID: 20250917153300
Revises:
Create Date: 2025-09-17 15:33:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20250917153300'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('status', sa.String(length=20), server_default='active', nullable=True))
    op.add_column('agents', sa.Column('endpoint', sa.String(length=500), nullable=True))
    op.add_column('agents', sa.Column('capabilities', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('agents', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('agents', sa.Column('health_check_url', sa.String(length=500), nullable=True))
    op.add_column('agents', sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True))
    op.add_column('agents', sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_column('agents', 'registered_at')
    op.drop_column('agents', 'last_heartbeat')
    op.drop_column('agents', 'health_check_url')
    op.drop_column('agents', 'metadata')
    op.drop_column('agents', 'capabilities')
    op.drop_column('agents', 'endpoint')
    op.drop_column('agents', 'status')
    # ### end Alembic commands ###